db:
  postgresql:
    uri: jdbc:postgresql://tai.db.elephantsql.com/ugynnzea
    user: ugynnzea
    pwd: 3boAI3TvmeEURbypvQVPcwGfEV1c1yPW
    port: 5432

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.postgresql.uri}
    username: ${db.postgresql.user}
    password: ${db.postgresql.pwd}
flyway:
  enabled: false
  url: ${db.postgresql.uri}
  user: ${db.postgresql.user}
  password: ${db.postgresql.pwd}
  schema: mega_schema
  baseline-on-migrate: false