db:
  postgresql:
    uri: postgres://tai.db.elephantsql.com/ugynnzea
    user: exazptjkljhadr
    pwd: 337d0dd270ea692dd35923984e2308d8087505fe94cdd1013e68cff5f9211ce9
    port: 5432

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.postgresql.uri}
    username: ${db.postgresql.user}
    password: ${db.postgresql.pwd}
